# Generated by Django 4.2.11 on 2024-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="skills",
            field=models.ManyToManyField(to="app.skills"),
        ),
    ]
